version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  # Uncomment this section if you want to add a database in the future
  # db:
  #   image: mysql:8.0
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: electroshop
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# Uncomment this section if you want to add a database in the future
# volumes:
#   db-data:
